=== schioler/event-reg/EventParent/EventBase/src/main/data/event-schema-0.6.xsd
<?xml version="1.0" ?>
<xsd:schema targetNamespace="http://www.schioler.dk/xsd/event" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:event="http://www.schioler.dk/xsd/event" elementFormDefault="qualified" attributeFormDefault="unqualified"
   version="0.6">

   <xsd:simpleType id="unit" name="unit">
      <xsd:restriction base="xsd:string">
         <xsd:enumeration value="kg"/>
         <xsd:enumeration value="g"/>
         <xsd:enumeration value="mg"/>
         <xsd:enumeration value="mcg"/>
         <xsd:enumeration value="lb"/>
         <xsd:enumeration value="oz"/>
         <xsd:enumeration value="l"/>
         <xsd:enumeration value="dl"/>
         <xsd:enumeration value="cl"/>
         <xsd:enumeration value="ml"/>
         <xsd:enumeration value="years"/>
         <xsd:enumeration value="months"/>
         <xsd:enumeration value="days"/>
         <xsd:enumeration value="hours"/>
         <xsd:enumeration value="minutes"/>
         <xsd:enumeration value="seconds"/>
         <xsd:enumeration value="drag"/>
         <xsd:enumeration value="registration"/>
      </xsd:restriction>
   </xsd:simpleType>

   <xsd:complexType name="event-template">
      <xsd:attribute name="name" type="xsd:string"></xsd:attribute>
      <xsd:attribute name="short-name" type="xsd:string"></xsd:attribute>
      <xsd:attribute name="unit" type="event:unit" use="required"></xsd:attribute>
      <xsd:attribute name="dose" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="description" type="xsd:string"/>
      <xsd:attribute name="is-favorite" type="xsd:boolean" default="false"></xsd:attribute>
   </xsd:complexType>
   <xsd:complexType name="event-type">
      <xsd:sequence maxOccurs="unbounded" minOccurs="0">
         <xsd:element name="event-template" type="event:event-template"></xsd:element>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="short-name" type="xsd:string" use="required"></xsd:attribute>
      <xsd:attribute name="description" type="xsd:string" use="optional"></xsd:attribute>
   </xsd:complexType>
   <xsd:element name="root">
      <xsd:complexType>
         <xsd:sequence maxOccurs="unbounded" minOccurs="1">
            <xsd:element name="event-type" type="event:event-type"></xsd:element>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
</xsd:schema>

=== schioler/event-reg/EventParent/EventTools/src/main/data/event-base-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<e:root xmlns:e="http://www.schioler.dk/event" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.schioler.dk/event ../schema/event-schema-0.6.xsd">
   <event-type short-name="MEDICIN-PARK" name="Medicin-parkinson">
      <event-template name="Sinemet 25/100" dose="25/100" unit="MILLIGRAM" short-name="SINE_25100"/>
       <event-template name="Sinemet halv" dose="23.5/50" unit="MILLIGRAM" short-name="SINE-EXT"/>
      <event-template name="Ropinirol 8mg" dose="8" unit="MILLIGRAM" short-name="ROPI-8"/>
      <event-template name="Ropinirol 8+2mg" dose="10" unit="MILLIGRAM" short-name="ROPI-8+2"/>
      <event-template name="Ongentsys" dose="50" unit="MILLIGRAM" short-name="ONGS-50"/>
      <event-template name="Madopar-Quick 62,5" dose="62.5" unit="MILLIGRAM" short-name="MADO-QUICK-62"/>
      <event-template name="Madopar-Quick 100" dose="100" unit="MILLIGRAM" short-name="MADO-QUICK-100"/>
      <event-template name="Entacapone" dose="200" unit="MILLIGRAM" short-name="ENTACAP-200"/>
      <event-template name="Dinetrel" dose="100" unit="MILLIGRAM" short-name="DINETREL-100"/>
   </event-type>
   <event-type name="Medicin-anden" short-name="MEDICIN-ANDEN">
      <event-template name="Betmiga 25mg" dose="25" unit="MILLIGRAM" short-name="BETM-25"/>
      <event-template name="Imozop 7.5mg" dose="7.5" unit="MILLIGRAM" short-name="IMOZ-7.5"/>
      <event-template name="Melatonin 2mg" dose="2" unit="MILLIGRAM" short-name="MELATONIN"/>
      <event-template name="Microlax" dose="100" unit="MILLILITER" short-name="MICROLAX"/>
      <event-template name="Kodipar 1stk" dose="500/30.6" unit="MILLIGRAM" short-name="KODIPAR_1STK"/>
      <event-template name="Kodipar + Panodil" dose="50/50" unit="MILLIGRAM" short-name="KODIPAR_PANO"/>
      <event-template name="Ipren" dose="200" unit="MILLIGRAM" short-name="IPREN"/>
      <event-template name="Ipren" dose="500" unit="MILLIGRAM" short-name="IPREN"/>
   </event-type>
   <event-type short-name="Medicin-alternativ" name="MEDICIN-ALTERNATIV">
      <event-template name="Hash" dose="1" unit="DRAG" short-name="HASH"/>
      <event-template name="Hash-karamel" dose="1" unit="PIECES" short-name="HASH-KAR"/>
      <event-template name="Melatonin" dose="10" unit="MILLIGRAM" short-name="MELA"/>
   </event-type>
   <event-type name="Behandling" short-name="BEHANDL">
      <event-template name="Fysioterapi - solo" dose="30" unit="MINUTES" short-name="FYS-SOLO"/>
      <event-template name="Fysioterapi - hold" dose="60" unit="MINUTES" short-name="FYS-HOLD"/>
      <event-template name="Zoneterapi" dose="70" unit="MINUTES" short-name="ZONET"/>
      <event-template name="Prakt.læge,konsultation" dose="20" unit="MINUTES" short-name="PRAKTISERENDE"/>
      <event-template name="Massage" dose="15" unit="MINUTES" short-name="MASSAGE"/>
      <event-template name="Massage" dose="30" unit="MINUTES" short-name="MASSAGE"/>
      <event-template name="Massage" dose="60" unit="MINUTES" short-name="MASSAGE"/>
   </event-type>
   <event-type name="Vitamin" short-name="VITAMIN">
      <event-template name="B12 1mg" dose="1" unit="MILLIGRAM" short-name="B12-1MG"/>
      <event-template name="Multi" dose="10" unit="MILLIGRAM" short-name="MULTI"/>
      <event-template name="Magnesia 2x500" dose="500" unit="MILLIGRAM" short-name="MAGNESIA"/>
      <event-template name="Olivir" dose="1" unit="MILLIGRAM" short-name="OLIVIR-XX"/>
   </event-type>
   <event-type name="Fysik" short-name="FYSIK">
      <event-template name="afføring" dose="STOR" unit="REGISTRATION" short-name="AFFØR-STOR"/>
      <event-template name="afføring" dose="MLM" unit="REGISTRATION" short-name="AFFØR-MLM"/>
      <event-template name="afføring" dose="LILLE" unit="REGISTRATION" short-name="AFFØR-LILLE"/>
      <event-template name="urinering" dose="STOR" unit="MILLILITER" short-name="URIN"/>
      <event-template name="urinering" dose="MLM" unit="MILLILITER" short-name="URIN"/>
      <event-template name="urinering" dose="LILLE" unit="MILLILITER" short-name="URIN"/>
      <event-template name="søvn" dose="4" unit="HOURS" short-name="SØVN"/>
      <event-template name="Væske-indtag" dose="0.5" unit="LITER" short-name="VÆSKE-IND"/>
   </event-type>
   <event-type name="Tilstand" short-name="TILSTAND">
      <event-template name="Fantastic - feeling free" dose="1" unit="REGISTRATION" short-name="STATE-10"/>
      <event-template name="Fantastic" dose="1" unit="REGISTRATION" short-name="STATE-09"/>
      <event-template name="Good - pretty good " dose="" unit="REGISTRATION" short-name="STATE-08"/>
      <event-template name="Good - can do stuff" dose="" unit="REGISTRATION" short-name="STATE-07"/>
      <event-template name="Not Good - hesitant on doing stuff" dose="" unit="REGISTRATION" short-name="STATE-06"/>
      <event-template name="Not Good - too warm, tired, ok movements" dose="" unit="REGISTRATION" short-name="STATE-05"/>
      <event-template name="Bad - too warm, no energy, reduced agility" dose="" unit="REGISTRATION" short-name="STATE-04"/>
      <event-template name="Bad - full stop" dose="" unit="REGISTRATION" short-name="STATE-03"/>
      <event-template name="Bad - want to lie down" dose="" unit="REGISTRATION" short-name="STATE-02"/>
      <event-template name="Bad - want to Die" dose="" unit="REGISTRATION" short-name="STATE-01"/>
   </event-type>
</e:root>

=== schioler/event-reg/EventParent/EventBase/src/main/data/nouse-event-base-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.schioler.dk/xsd/event"
   xsi:schemaLocation="http://www.schioler.dk/xsd/event ./event-schema-0.6.xsd">
   <event-type name="Medicin-parkinson" short-name="MEDICIN-PARK">
      <event-template name="Sinemet 25/100" dose="25/100" unit="mg" short-name="SINE_25100"
         is-favorite="true"/>
      <event-template name="Sinemet halv" dose="23.5/50" unit="mg" short-name="SINE-EXT"/>
      <event-template name="Ropinirol 8mg" dose="8" unit="mg" short-name="ROPI-8" is-favorite="true"/>
      <event-template name="Ropinirol " dose="10" unit="mg" short-name="ROPI-8+2"/>
      <event-template name="Ongentsys" dose="50" unit="mg" short-name="ONGS-50"/>
      <event-template name="Madopar-Quick" dose="62.5" unit="mg" short-name="MADO-QUICK-62"
         is-favorite="true"/>
      <event-template name="Entacapone" dose="200" unit="mg" short-name="ENTACAP-200"/>
   </event-type>
   <event-type name="Medicin-anden" short-name="MEDICIN-ANDEN">
      <event-template name="Betmiga 25mg" dose="25" unit="mg" short-name="BETM-25" is-favorite="true"/>
      <event-template name="Imozop 7.5mg" dose="7.5" unit="mg" short-name="IMOZ-7.5"/>
      <event-template name="Melatonin 2mg" dose="2" unit="mg" short-name="MELATONIN"/>
      <event-template name="Microlax" dose="25" unit="ml" short-name="MICROLAX"/>
      <event-template name="Kodipar 1stk" dose="500/30.6" unit="mg" short-name="KODIPAR_1STK"/>
      <event-template name="Kodipar + Panodil" dose="50" unit="mg" short-name="KODIPAR_PANO"/>
      <event-template name="Ipren" dose="200" unit="mg" short-name="IPR200"/>
      <event-template name="Ipren" dose="500" unit="mg" short-name="IPR500"/>
      <event-template name="Betolvex" dose="1" unit="mg" short-name="B12"/>
   </event-type>
   <event-type name="Behandling" short-name="BEHANDL">
      <event-template name="Fysioterapi - solo" dose="30" unit="minutes" short-name="FYS-SOLO"/>
      <event-template name="Fysioterapi - hold" dose="60" unit="minutes" short-name="FYS-HOLD"/>
      <event-template name="Zoneterapi" dose="70" unit="minutes" short-name="ZONET"/>
      <event-template name="Praktiserende læge" dose="20" unit="minutes" short-name="PRAKTISERENDE"/>
      <event-template name="Massage" dose="15" unit="minutes" short-name="MASSAGE"/>
      <event-template name="Hash" dose="1" unit="drag" short-name="HASH"/>
   </event-type>
   <event-type name="Vitamin" short-name="VITAMIN">
      <event-template name="B12" dose="1" unit="mg" short-name="B12-1MG"/>
      <event-template name="Multi" dose="10" unit="mg" short-name="MULTI"/>
      <event-template name="Magnesia 2x500" dose="500" unit="mg" short-name="MAGNESIA"/>
      <event-template name="Olivir" dose="50" unit="mg" short-name="OLIVIR-XX"/>
   </event-type>
   <event-type name="Fysik" short-name="FYSIK">
      <event-template name="afføring" dose="STOR" unit="ml" short-name="AFFØR-STOR"/>
      <event-template name="afføring" dose="MLM" unit="ml" short-name="AFFØR-MLM"/>
      <event-template name="afføring" dose="LILLE" unit="ml" short-name="AFFØR-LILLE"/>
      <event-template name="urinering" dose="STOR" unit="ml" short-name="URIN"/>
      <event-template name="urinering" dose="MLM" unit="ml" short-name="URIN"/>
      <event-template name="urinering" dose="LILLE" unit="ml" short-name="URIN"/>
      <event-template name="søvn" dose="4" unit="hours" short-name="SØVN"/>
      <event-template name="Væske-indtag" dose="0.5" unit="l" short-name="VÆSKE-IND"/>
      <event-template name="Hash" dose="1" unit="drag" short-name="HASH"/>
   </event-type>
   <event-type name="Tilstand" short-name="TILSTAND">
      <event-template name="Fantastic - feeling free" dose="n/a" unit="registration"
         short-name="STATE-10"/>
      <event-template name="Fantastic" dose="n/a" unit="registration" short-name="STATE-09"/>
      <event-template name="Good - pretty good " dose="n/a" unit="registration" short-name="STATE-08"/>
      <event-template name="Good - can do stuff" dose="n/a" unit="registration" short-name="STATE-07"/>
      <event-template name="Could be better - hesitant on doing stuff" dose="n/a" unit="registration"
         short-name="STATE-06"/>
      <event-template name="Could be better - too warm, tired, ok movements" dose="n/a"
         unit="registration" short-name="STATE-05"/>
      <event-template name="Bad - too warm, no energy, reduced agility" dose="n/a" unit="registration"
         short-name="STATE-04"/>
      <event-template name="Bad - full stop" dose="n/a" unit="registration" short-name="STATE-03"/>
      <event-template name="Bad - want to lie down" dose="n/a" unit="registration" short-name="STATE-02"/>
      <event-template name="Bad - want to Die" dose="n/a" unit="registration" short-name="STATE-01"/>
   </event-type>
</root>
